// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0btJKi7yD7grNVYCezCVRVwfMh6fFDs',
    appId: '1:944674009864:web:cd63ad17c8e08549f0b2bd',
    messagingSenderId: '944674009864',
    projectId: 'safemom-bd26b',
    authDomain: 'safemom-bd26b.firebaseapp.com',
    storageBucket: 'safemom-bd26b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxe2YjI18vrbaRgw5c3_4MRnDi8AaPuO8',
    appId: '1:944674009864:android:82bf5888e1c96c63f0b2bd',
    messagingSenderId: '944674009864',
    projectId: 'safemom-bd26b',
    storageBucket: 'safemom-bd26b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBxfxXTcr4NXis95j3moKJPmJyUxc_pY',
    appId: '1:944674009864:ios:55a5b195b3aefe64f0b2bd',
    messagingSenderId: '944674009864',
    projectId: 'safemom-bd26b',
    storageBucket: 'safemom-bd26b.firebasestorage.app',
    iosClientId: '944674009864-i7tu6f3s1cc2pa95niseipm5fg85khvg.apps.googleusercontent.com',
    iosBundleId: 'rw.alu.safemom.safemom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBxfxXTcr4NXis95j3moKJPmJyUxc_pY',
    appId: '1:944674009864:ios:55a5b195b3aefe64f0b2bd',
    messagingSenderId: '944674009864',
    projectId: 'safemom-bd26b',
    storageBucket: 'safemom-bd26b.firebasestorage.app',
    iosClientId: '944674009864-i7tu6f3s1cc2pa95niseipm5fg85khvg.apps.googleusercontent.com',
    iosBundleId: 'rw.alu.safemom.safemom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB0btJKi7yD7grNVYCezCVRVwfMh6fFDs',
    appId: '1:944674009864:web:1e788d0134b70946f0b2bd',
    messagingSenderId: '944674009864',
    projectId: 'safemom-bd26b',
    authDomain: 'safemom-bd26b.firebaseapp.com',
    storageBucket: 'safemom-bd26b.firebasestorage.app',
  );
}
